# Generated by Django 3.2.4 on 2021-06-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0002_alter_profile_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
